# Generated by Django 5.2.1 on 2025-05-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to='products/')),
            ],
        ),
    ]
